### ISSUE TITLE
Use with 11ty vite?

### ISSUE THREAD

**Issue by simplerethink** [proog/eleventy-plugin-purgecss#5]
Can this be used with the 11ty Vite plugin? 

It doesn't appear to be purging unused css.

**Comment by proog** [comment]
Unfortunately, I haven't tried this myself, so I don't know.

As Vite [supports PostCSS](https://vitejs.dev/guide/features.html#postcss) out of the box, you might have more luck using the [postcss-purgecss plugin](https://purgecss.com/plugins/postcss.html) directly with Vite 🙂
