### ISSUE TITLE
Compatibility with 11ty 3 ESM (module) mode

### ISSUE THREAD

**Issue by notacouch** [proog/eleventy-plugin-purgecss#7]
Hello,

I am using 11ty 3 alpha5 with ESM (type: "module") mode enabled. Doesn't seem like this works with it even if the config file is in ESM:
![image](https://github.com/proog/eleventy-plugin-purgecss/assets/2334143/795f0d13-5720-47d8-9850-586b4cb38dff)

> [11ty] Error loading the config file require() of ES Module ...\11ty\purgecss.config.js from ...\11ty\node_modules\purgecss\lib\purgecss.js not supported.
> [11ty] Instead change the require of purgecss.config.js in ...\11ty\node_modules\purgecss\lib\purgecss.js to a dynamic import() which is available in all CommonJS modules. (via Error)

**Comment by proog** [comment]
Hi!

This seems to be a limitation of PurgeCSS, as its CLI has the same issue. It attempts to `require()` the config file even when used in an ESM context.

As a workaround, try changing the config file extension to `.cjs` and specifying it explicitly:

```js
eleventyConfig.addPlugin(purgeCssPlugin, {
  config: "./purgecss.config.cjs"
});
```

**Comment by proog** [comment]
I'm closing this, let me know if the suggestion didn't solve the issue :)

**Comment by notacouch** [comment]
I appreciate your prompt response back in March. I haven't had the opportunity yet to test but will definitely keep you posted once I have.
